"""add relationship

Revision ID: 9fafc1af6479
Revises: c691dc343851
Create Date: 2025-11-04 12:16:40.396574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fafc1af6479'
down_revision: Union[str, Sequence[str], None] = 'c691dc343851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_foreign_key('users_institution_id_fkey', 'users', 'institution', ['institution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_institution_id_fkey', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_column('users', 'institution_id')
    # ### end Alembic commands ###
