"""add institution and schemas

Revision ID: c691dc343851
Revises: a7249b9f4d01
Create Date: 2025-11-04 11:58:36.454631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c691dc343851'
down_revision: Union[str, Sequence[str], None] = 'a7249b9f4d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('instagram', 'evolution', 'whatsapp', 'email', 'api', name='provider_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('institution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('channel_type_id', sa.Integer(), nullable=False),
    sa.Column('post_endpoint', sa.String(length=1024), nullable=True),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_type_id'], ['channel_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channels_created_at', 'channels', ['created_at'], unique=False)
    op.create_index('ix_channels_type', 'channels', ['channel_type_id'], unique=False)
    op.create_table('channel_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.Enum('API_KEY', 'TOKEN', 'BASIC_AUTH', 'OAUTH', 'SECRET', name='credential_type_enum'), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'credential_type', 'active', name='uq_channel_cred_active_one_per_type')
    )
    op.create_index('ix_channel_credentials_active', 'channel_credentials', ['active'], unique=False)
    op.create_index('ix_channel_credentials_channel', 'channel_credentials', ['channel_id'], unique=False)
    op.create_index('ix_channel_credentials_expires_at', 'channel_credentials', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_channel_credentials_expires_at', table_name='channel_credentials')
    op.drop_index('ix_channel_credentials_channel', table_name='channel_credentials')
    op.drop_index('ix_channel_credentials_active', table_name='channel_credentials')
    op.drop_table('channel_credentials')
    op.drop_index('ix_channels_type', table_name='channels')
    op.drop_index('ix_channels_created_at', table_name='channels')
    op.drop_table('channels')
    op.drop_table('institution')
    op.drop_table('channel_type')
    # ### end Alembic commands ###
